### ISSUE TITLE
Error on GET_ABUNDANT_ANCHORS - exit status (2)

### ISSUE THREAD

**Issue by durrantmm** [salzmanlab/nomad#40]
I've been running NOMAD on a collection of 50 Vibrio cholerae isolates to identify hypervariable regions. 

This is the command I run:
```
nextflow run salzmanlab/nomad \
    -profile docker \
    -r main \
    -latest \
    -resume \
    --input OUTPUT/samples/PRJNA668606.paths.filt.nf.csv \
    --element_annotations_samplesheet OUTPUT/annot.txt \
    --run_annotations false
```

There is no relevant annotation file, so I include a placeholder file and I set ` --run_annotations false`.

And this is the error I get, apologies for just posting the screenshot:

![image](https://user-images.githubusercontent.com/10098419/196089602-1be3ca82-f65e-4908-8f53-457382e8f0f7.png)

I'm running this on google cloud VM running Ubuntu 18.04.

**Comment by kaitlinchaung** [comment]
Hi, could you please post the entire message? Thanks!

**Comment by durrantmm** [comment]
Apologies, I figured it out! Requires more disk space than I expected.

Thank you.
